/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: "category",
      label: "BlockID Developer SDK",
      items: ["index"],
    },
    {
      type: "category",
      label: "BlockID Universal Web Login (UWL)",
      items: ["uwl/uwl1"],
    },
    {
      type: "category",
      label: "BlockID One-Time Passcodes (OTP)",
      items: ["otp/otp1", "otp/otp2", "otp/otp3"],
    },
    //will show in future time
    // {
    //   type: "category",
    //   label: "BlockID Developer API",
    //   items: ["api/api1", "api/otp/api2"],
    // },
    // By default, Docusaurus generates a sidebar from the docs folder structure
    /*tutorialSidebar: [
    {
      type: 'autogenerated', dirName: '.'
    }
  ],
*/
    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
  ],
};

module.exports = sidebars;
